#!/usr/bin/with-contenv bash

echo "Start OpenVPN Client."
echo "Start options : ${RUN_OPTS}"

[ "${RUN_OPTS}" = "" ] && exec s6-setuidgid abc /app/openvpn.sh
    || exec s6-setuidgid abc /app/openvpn.sh ${RUN_OPTS}
