#!/usr/bin/with-contenv bash

echo "Start OpenVPN Client."

# NOTE : openvpn client binary must be run with root
if [ "${RUN_OPTS}" = "" ]; then
    /app/openvpn.sh
else
    /app/openvpn.sh ${RUN_OPTS}
fi


